### ISSUE TITLE
Core issues

### ISSUE THREAD

**Issue by steelmm09** [sy2002/zxuno4mega65#15]
New Version of mega65 2nd batch release,,all version of cores do not work or start using internal sdcards as per intsructions given

**Comment by sy2002** [comment]
@steelmm09 I am not sure if you saw my Discord message (I tagged you assuming you are @steelers2000 on Discord.

https://discord.com/channels/719326990221574164/794775503818588200/1073912828160917574

I am asking because I did not see feedback from you in the #other-cores channel regarding my message.

Copying the gist of the message here for your convenience:

* [Please use this version of the core](https://github.com/sy2002/zxuno4mega65/raw/reset-workaraound/bin/R3/ZXUNO4M65-MAX10-fix.cor)

* **Never use SDXC cards.** Not for the ZX spectrum core, but also not for the MEGA65 or the C64 core. **Stick to cards with a maximum size of 32 GB.** And use "brands" no "no-name" cards. The SD card reading is quite fragile unfortunately. Quoting the tutorial Wiki from the ZX Spectrum: "If you decide to use a new card, then make sure that it is a SDHC card between 4 GB and 32 GB formatted as FAT32."

* Make sure you use the internal SD card slot of the MEGA65 (at the bottom inside the tray), as the ZX Uno core is not supporting yet the external SD card slot

* Solve any HDMI backpower issue because HDMI backpower leads - among other things - to SD card reading bugs. Have a look at the FAQ for the C64 core, if you're new to the "HDMI backpower issue" - it also applies to the ZX spectrum core and also applies when you are using the VGA output but have the HDMI cable plugged in: https://github.com/MJoergen/C64MEGA65/blob/master/FAQ.md

I am closing this issue because I suspect that one of the above-mentioned hints will solve your problem. If not - please re-open.

**Comment by steelmm09** [comment]
hello thanks for the reply but i have still have the same issues with th max10 core no screen or boot with a sandisk 32gb card as formatted within the machine itself all other cores work fine except this speccy version my motherboard is the latest r3 revision i have now used various other brands of sd card in which this is not the issue maybe the motherboard has changed on this 2nd batch or the firmware from factory was changed to another revision

thanks

**Comment by steelmm09** [comment]
your other core works fine the Gameboy onee  i installed r2 for that.

**Comment by sy2002** [comment]
@steelmm09 Thank you for the update. Just for clarity: For the GameBoy you installed the R3 version, right? Because you for sure have a R3A and not a R2. The GameBoy R2 core wouldn't even start on your R3A machine.

And regarding Speccy: You used the MAX10 core (downloadlink: scroll up) and you did format the 32 GB SD card with FAT32 AND you did copy all the necessary files as described [here in the Wiki](https://github.com/sy2002/zxuno4mega65/wiki/Getting-Started#1-prepare-an-sd-card), i.e. you:

* Downloaded ExDos 0.8.8 and unzipped it
* Made sure you have the folders BIN, SYS and TMP with the right ExDos
* etc.

?

If so: Can you please make a video with your mobile phone and upload it somewhere and send me a link? The video should show what's on your SD card, how you start the MEGA65 and what exactly happens.

P.S. You are ware of the HDMI backpower problem and that HDMI backpower prevents SD card reading? Read this here:
https://github.com/MJoergen/C64MEGA65/blob/master/FAQ.md

**Comment by steelmm09** [comment]
Hi sy2002


Many thanks for your replyplease close the request as problem sorted out

It was my old TV monitor Sanyo 16.9,,I was using I plugged I hp monitor
using VGA and works with your core fix version.


Cheers

**Comment by sy2002** [comment]
@steelmm09 Thank you for your feedback! These are great news! 👍🏻 I am super happy to hear that the core works for you.

**Comment by steelmm09** [comment]
Yes thanks for all your hard work it's greatly appreciated.



Cheers again.
