### ISSUE TITLE
Barcode issue

### ISSUE THREAD

**Issue by Kugelblitz360** [sy2002/zxuno4mega65#18]
It looks like this core also shows the "barcode" issue that appears on some R6 machines with the C64 core.

**Comment by sy2002** [comment]
Thank you @Kugelblitz360: Yes, this is VERY plausible, as the ZX-Uno core uses the very same MiSTer2MEGA65 release version as the C64 core - which is 2.0.0 - and this release version is having the "barcode" problem.

I will port the experimental fix we did for the C64 to M2M and/or this core, too to fix it.

**Comment by sy2002** [comment]
[hdmi-fix.zip](https://github.com/user-attachments/files/17346318/hdmi-fix.zip)

The attached ZIP should fix it. I shared the fix with "captaincommodore" on Discord (https://discord.com/channels/719326990221574164/1262500939701420114/1294367773438513152) so that he can confirm that the fix actually works.

**Comment by sy2002** [comment]
Two people on Discord confirm, that V1.3 fixes the issue:

https://discord.com/channels/719326990221574164/1262500939701420114/1294413662588637194

and

https://discord.com/channels/719326990221574164/1262500939701420114/1294650978280411210
